services:
  db:
    image: mysql:8.0
    container_name: mysql-enerlink
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ENERLINK
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  api:
    build: . # Diz para o Docker procurar o Dockerfile na mesma pasta
    container_name: api-enerlink
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db # Garante que o banco suba antes da API
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${DB_DRIVER}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true